### ISSUE TITLE
Documento de Requisitos do Sistema

### ISSUE THREAD

**Issue by Durfan** [Durfan/ufsj-tp-autoimports#1]
Elaborar os requisitos de acordo com o [Template: Software Requirements Specification.odt](https://github.com/Durfan/ufsj-tp-autoimports/blob/master/contabilidade/Software%20Requirements%20Specification.odt)

**Comment by Durfan** [comment]
O modelo para a doc de requisitos foi postado no campusvirtual: [Projeto-GaEl.pdf](https://www.campusvirtual.ufsj.edu.br/portal/2019_2/pluginfile.php/72200/mod_resource/content/1/Projeto-GaEl.pdf). Vou transferir para o overleaf e disponibilizar.

**Comment by antonio258** [comment]
Não sei se o Pablo já passou pro Overleaf, então ta ae https://pt.overleaf.com/9315855369trwcwmwnzmfr
falta editar ainda pq só converti pra .tex

**Comment by Durfan** [comment]
As modificações revistas na entrevista precisam ser aplicadas na doc.

**Comment by Durfan** [comment]
Due!
